# Generated by Django 5.2.1 on 2025-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='books/images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs/'),
        ),
    ]
